### ISSUE TITLE
Image manipulation service

### ISSUE THREAD

**Issue by martywallace** [martywallace/tempest#70]
Create a service that provides basic image manipulation, similar to Craft's ImageModel. The service should allow:
- [ ] Image cropping & scaling.
- [ ] Basic compression for JPEGs.
- [ ] Create empty images for placeholding etc.

Generated images should be saved and re-used for each transform combination.

**Comment by MartyWallace** [comment]
Include reference to Base64 data for 1x1 transparent pixel image:

    data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7

**Comment by MartyWallace** [comment]
Wrap [Cloudinary](http://cloudinary.com/documentation/php_integration#getting_started_guide), saves me having to implement anything and it looks pretty decent. KeystoneJS uses it too.
